In [2]:
import numpy as np

a = np.array([0,1,2,3])
print(a)
print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [6]:
L= range(1000)
%timeit[i**2 for i in L]



672 µs ± 2.08 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [9]:
a = np.arange(1000)
%timeit a**2

2.78 µs ± 39.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [12]:
a = np.array([0,1,2,3])
a
print(a)

[0 1 2 3]


In [13]:
a

array([0, 1, 2, 3])

In [14]:
a.ndim

1

In [15]:
len(a)

4

In [16]:
# 2D and 3D array creation
b = np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
print(b)

[[0 1 2]
 [3 4 5]]


In [18]:
b.ndim


2

In [21]:
len(b)

2

In [23]:
print("b shape ", b.shape)
print("a shape ", a.shape)


b shape  (2, 3)
a shape  (4,)


In [24]:
a = np.array([[0,1] ,[2,3] ,[4,5] ])
print(a)

[[0 1]
 [2 3]
 [4 5]]


In [25]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [28]:
a.ndim
c = np.array([[[0,1], [2,3]] ,[[4,5] ,[6,7] ]  ])
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [29]:
print(c)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [30]:
c.ndim

3

In [31]:
c.shape

(2, 2, 2)

In [33]:
#using arrange functions

a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
b = np.arange(1,10, 2)

In [35]:
b

array([1, 3, 5, 7, 9])

In [46]:
a =  np.linspace(0,5,6)
a


array([0., 1., 2., 3., 4., 5.])

In [50]:
#common arrays

a = np.ones((3,3))
a
a = np.ones((2,2))
a

array([[1., 1.],
       [1., 1.]])

In [57]:
a = np.arange(0,10)
print(a)
b = np.array([[1,2,3] , [4,5,6]])
print(b)

[0 1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]]


In [58]:
a = np.zeros((3,3))

In [59]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [60]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [63]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [64]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [65]:
np.eye(2,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [69]:
print(a)
a.shape

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


(3, 3)

In [70]:
a = np.ones((2,4))

In [71]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [73]:
a.shape


2

In [74]:
a.ndim


2

In [87]:
b = np.zeros((4,3))
print(b, "    ", a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]      [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [88]:
print(b.shape)
print(a.shape)
print(b.ndim)
print(a.ndim)

(4, 3)
(2, 4)
2
2


In [93]:
c3d = np.array([[1,2] ,[1,3] ,[1,4] ])

In [90]:
c3d

array([[1, 2],
       [1, 3],
       [1, 4]])

In [91]:
c3d.ndim

2

In [94]:
a = np.ones((3,3))

In [95]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [96]:
a = np.zeros((2,2))

In [97]:
a

array([[0., 0.],
       [0., 0.]])

In [98]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [99]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [100]:
a = np.diag([1,2,3,4,5])

In [101]:
a.shape

(5, 5)

In [102]:
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [103]:
np.diag(a)

array([1, 2, 3, 4, 5])

In [104]:
a = np.eye(3)

In [105]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [106]:
np.diag(b)

array([0., 0., 0.])

In [107]:
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [108]:
b = np.diag([1,2,3,4])

In [111]:
b = np.diag([5,5,5,5,5])

In [112]:
b

array([[5, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 5]])

In [113]:
#creating array using random

a = np.random.rand(4)

In [114]:
a

array([0.82742413, 0.65482676, 0.80648583, 0.07565469])

In [115]:
b = np.random.randn(4)

In [116]:
b

array([-0.58274672,  0.9988448 , -1.47434504,  0.02223531])

In [117]:
a = np.arange(10)

In [118]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
a.dtype

dtype('int32')

In [120]:
b = np.arange(10, dtype = 'float64')

In [121]:
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [122]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [125]:
#complex data types

d = np.array([1+2j , 2+4j])
print(d.dtype)
d

complex128


array([1.+2.j, 2.+4.j])

In [128]:
d = np.array([True, False, True, False])
d

array([ True, False,  True, False])

In [129]:
d.dtype

dtype('bool')

In [130]:
st = np.array(['ash', 'neel', 'welcome', 'gudLuck'])

In [131]:
st.dtype

dtype('<U7')

In [132]:
st

array(['ash', 'neel', 'welcome', 'gudLuck'], dtype='<U7')

In [133]:
ab = np.arange(10)

In [134]:
ab

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
print(ab[5])

5


In [136]:
print(ab[5]+10)

15


In [137]:
ab[4] + 2

6

In [145]:
a = np.diag([1,2,3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [146]:
print(a[2,2])

3


In [147]:
a[1,2] = 5

In [148]:
a

array([[1, 0, 0],
       [0, 2, 5],
       [0, 0, 3]])

In [151]:
#slicing in matrix

a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [152]:
a[1:8:2]

array([1, 3, 5, 7])

In [158]:
a[0:12:3]

array([0, 3, 6, 9])

In [159]:
a = np.arange(10)

In [160]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [168]:
a[5 : : ] = 10

In [169]:
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [174]:
b = np.arange(5)

In [180]:
b

array([0, 1, 2, 3, 4])

In [183]:
a[5:] = b[::-1]

In [184]:
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [185]:
# Copies and Views

a = np.arange(10)

In [186]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [188]:
b = a[::2]

In [189]:
b

array([0, 2, 4, 6, 8])

In [190]:
np.shares_memory(a,b)

True

In [191]:
b[0] = 100

In [192]:
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [193]:
b

array([100,   2,   4,   6,   8])

In [194]:
aa = np.arange(10)

In [196]:
bb = aa[::2].copy()

In [197]:
aa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [198]:
bb

array([0, 2, 4, 6, 8])

In [199]:
np.shares_memory(aa,bb)

False

In [200]:
bb[0] = 55

In [201]:
bb

array([55,  2,  4,  6,  8])

In [202]:
aa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [203]:
aa[0] = 101

In [204]:
aa

array([101,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [205]:
bb

array([55,  2,  4,  6,  8])

In [212]:
#fancy Indexing

a = np.random.randint(0,20,15)

In [213]:
a


array([ 4, 11,  9, 18, 15, 18,  2, 10, 15,  2, 19, 12,  6, 15, 19])

In [214]:
mask = (a%2 == 0)

In [215]:
mask

array([ True, False, False,  True, False,  True,  True,  True, False,
        True, False,  True,  True, False, False])

In [216]:
extract_from_a = a[mask]

In [217]:
extract_from_a

array([ 4, 18, 18,  2, 10,  2, 12,  6])

In [221]:
a[mask] = -55

In [222]:
mask

array([ True, False, False,  True, False,  True,  True,  True, False,
        True, False,  True,  True, False, False])

In [223]:
a

array([-55,  11,   9, -55,  15, -55, -55, -55,  15, -55,  19, -55, -55,
        15,  19])

In [226]:
a = np.arange(0,100,15)

In [227]:
a

array([ 0, 15, 30, 45, 60, 75, 90])

In [228]:
# Numerical Operations

a

array([ 0, 15, 30, 45, 60, 75, 90])

In [232]:
a = np.arange(0,101,10)

In [233]:
a


array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [234]:
a[[2,3,4,5]]

array([20, 30, 40, 50])

In [235]:
a[[2,3]]

array([20, 30])

In [236]:
a[[6,10]]

array([ 60, 100])

In [238]:
a[[2,2]]

array([20, 20])

In [243]:
a[[3, 4]]

array([30, 40])

In [244]:
a[[6,7]] = 555

In [245]:
a

array([  0,  10,  20,  30,  40,  50, 555, 555,  80,  90, 100])

In [246]:
a[[1,3,5,7,9]] = 999

In [247]:
a

array([  0, 999,  20, 999,  40, 999, 555, 999,  80, 999, 100])

In [248]:
#numpy operations

a = np.array([1,2,3,4])

In [249]:
a

array([1, 2, 3, 4])

In [250]:
a+1 

array([2, 3, 4, 5])

In [251]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [252]:
b = a+1

In [253]:
a

array([1, 2, 3, 4])

In [254]:
b

array([2, 3, 4, 5])

In [255]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [256]:
a

array([1, 2, 3, 4])

In [266]:
b = np.ones((4))+1

In [267]:
b

array([2., 2., 2., 2.])

In [268]:
a

array([1, 2, 3, 4])

In [269]:
b

array([2., 2., 2., 2.])

In [270]:
ab

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [271]:
a-b

array([-1.,  0.,  1.,  2.])

In [272]:
a*b

array([2., 4., 6., 8.])

In [273]:
a = np.ones((2,2))+2

In [274]:
a

array([[3., 3.],
       [3., 3.]])

In [275]:
b = np.ones((1,3))+2

In [278]:
# Matrix Multiplication

c = np.diag([1,2,3,4])

In [279]:
c

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [280]:
print(c*c)

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [281]:
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [283]:
#comparisons
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])
a == b

array([False,  True, False,  True])

In [286]:
np.array_equal(a,b)

False

In [288]:
a>=b

array([False,  True,  True,  True])

In [291]:
#array wise comparisons

a = np.array([1,2,3,4])
b = np.array([5,2,2,4])
c = np.array([1,2,3,4])

np.array_equal(a,b)
np.array_equal(a,c)

True

In [292]:
#logical Operators

a = np.array([1,1,0,0])
b = np.array([1,0,1,0])
np.logical_or(a,b)

array([ True,  True,  True, False])

In [293]:
np.logical_and(a,b)

array([ True, False, False, False])

In [296]:
#Transcendantal Functions

a = np.arange(5)

In [297]:
a

array([0, 1, 2, 3, 4])

In [298]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [299]:
a

array([0, 1, 2, 3, 4])

In [300]:
np.log(a)

C:\Users\swetha\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [301]:
a = np.arange(1,5)

In [302]:
a

array([1, 2, 3, 4])

In [303]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [304]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [305]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [306]:
#shape Mismatch

a = np.arange(4)

In [307]:
a

array([0, 1, 2, 3])

In [309]:
a + np.arange([3,2])

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [312]:
b = np.array([3,2])

In [313]:
b

array([3, 2])

In [314]:
a + b

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [315]:
#Basic reductions

#Computing sums
x = np.array([1,2,3,4])


In [316]:
np.sum(x)

10

In [318]:
x = np.array([[1,1], [2,2]])
x

array([[1, 1],
       [2, 2]])

In [319]:
x.sum(axis = 0)

array([3, 3])

In [320]:
x.sum(axis =1 )

array([2, 4])

In [323]:
axis = 0

In [324]:
#other reductions

x = np.array([1,3,2])


In [326]:
x

array([1, 3, 2])

In [327]:
x.min()

1

In [328]:
x.max()

3

In [329]:
x.argmin()

0

In [330]:
x.argmax()

1

In [331]:
x.argmax()-1

0

In [334]:
x = np.array([5,9, 7])

In [335]:
x.argmin()

0

In [337]:
x.argmax()

1

In [338]:
x.argmax()-1

0

In [339]:
x.argmax() -3

-2

In [340]:
#logical operations

np.all([True, True, True])

True

In [341]:
np.all([True,False,True])

False

In [342]:
np.all([False,False,False])

False

In [343]:
np.any([False,False,False])

False

In [345]:
np.any([True, False,False, True])

True

In [346]:
a = np.zeros((50,50))

In [347]:
a

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [348]:
np.any(a!=0)

False

In [349]:
np.all(a==a)

True

In [350]:
a[3][2]

0.0

In [351]:
a[3][2] =4

In [352]:
np.any(a!=0)

True

In [353]:
np.all(a!=0)

False

In [354]:
np.all(a==0)

False

In [359]:
a = np.array([2,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])

((a<=b) & (b <=c)).all()

True

In [358]:
    (b <=c)

array([ True,  True,  True,  True])

In [363]:
#Statistics

x = np.array([1,2,3,4])
y = np.array([[1,2,3], [5,6,7]])
x.mean()

2.5

In [364]:
np.median(x)

2.5

In [365]:
np.median(y,)

4.0

In [366]:
np.median(y, axis = -1)

array([2., 6.])

In [368]:
x.std()

1.118033988749895

In [370]:
#Example

# data in Populations.txt 

# loading data into numpy array object

data = np.loadtxt("populations.txt")



In [371]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [372]:
year, hares, lynxes, carrots = data.T

In [373]:
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [374]:
populations = data[:, 1 :]

In [375]:
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [376]:
populations.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [377]:
np.argmax(populations, axis =1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2],
      dtype=int64)

In [378]:
#Broadcasting

a = np.tile(np.arange(0,40,10) , (3,1))

In [379]:
a

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [382]:
print(b)

(array([ 0, 10, 20, 30]), (3, 1))


In [388]:
a = np.tile(np.arange(0,40,10) ,  (3,1))

In [389]:
a

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [390]:
a = a.T

In [391]:

a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [397]:
b = np.tile(np.arange(0,3,1) , (4,1))

In [398]:
b

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [399]:
b = np.array([0,1,2])

In [400]:
b

array([0, 1, 2])

In [401]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [402]:
b

array([0, 1, 2])

In [403]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [404]:
a*b

array([[ 0,  0,  0],
       [ 0, 10, 20],
       [ 0, 20, 40],
       [ 0, 30, 60]])

In [405]:
a/b

C:\Users\swetha\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\swetha\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan,  0.,  0.],
       [inf, 10.,  5.],
       [inf, 20., 10.],
       [inf, 30., 15.]])

In [407]:
a = np.tile(np.arange(0,40,10), (3,1))

In [408]:
a

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [410]:
a = a.T

In [411]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [412]:
b = np.array([0,1,2])

In [413]:
b

array([0, 1, 2])

In [414]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [415]:
a = np.tile(np.arange(0,40,10), (3,1))

In [417]:
b = np.tile(np.array([0,1,2]), (1,1))

In [418]:
b

array([[0, 1, 2]])

In [421]:
a = np.tile(np.arange(0,40,10) , (1,1))

In [422]:
a

array([[ 0, 10, 20, 30]])

In [423]:
a = a.T

In [424]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [425]:
a.shape

(4, 1)

In [430]:
c = np.arange(0,40,10)

In [431]:
c

array([ 0, 10, 20, 30])

In [432]:
c.shape

(4,)

In [433]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [437]:
c = c[:, np.newaxis]

In [438]:
c.shape

(4, 1)

In [439]:
c

array([[ 0],
       [10],
       [20],
       [30]])

In [441]:
a = np.arange(0,40,10)

In [442]:
a

array([ 0, 10, 20, 30])

In [443]:
a.shape

(4,)

In [444]:
a = a[ :, np.newaxis]

In [445]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [446]:
a.shape

(4, 1)

In [450]:
#Array shape manipulation

#Flattening
a = np.array([[1,2,3], [4,5,6]])
a


array([[1, 2, 3],
       [4, 5, 6]])

In [451]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [452]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [453]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [454]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [455]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [456]:
#reshaping

print(a)

[[1 2 3]
 [4 5 6]]


In [457]:
print(a.shape)

(2, 3)


In [458]:
b= a.ravel()

In [459]:
print(b)

[1 2 3 4 5 6]


In [461]:
b.shape

(6,)

In [462]:
b = b.reshape((2,3))

In [463]:
print(b)

[[1 2 3]
 [4 5 6]]


In [464]:
b.shape

(2, 3)

In [466]:
b = b.reshape(1,6)

In [467]:
b

array([[1, 2, 3, 4, 5, 6]])

In [468]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [469]:
b = b.reshape(3,2)

In [470]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [471]:
b[0,0]

1

In [476]:
b[0,1] = 200

In [477]:
b

array([[  1, 200],
       [  3,   4],
       [  5,   6]])

In [478]:
a = np.zeros((3,2))

In [479]:
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [486]:
b = a.T.reshape(3*2)

In [487]:
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [488]:
b

array([0., 0., 0., 0., 0., 0.])

In [489]:
b[0] = 50


In [490]:
b

array([50.,  0.,  0.,  0.,  0.,  0.])

In [491]:
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [492]:
#Adding a dimension

z = np.array([1,2,3])
z

array([1, 2, 3])

In [493]:
z[ :, np.newaxis]

array([[1],
       [2],
       [3]])

In [494]:
#Dimension Shuffling

a = np.arange(4*3*2).reshape(4,3,2)

In [495]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [496]:
a.shape

(4, 3, 2)

In [497]:
a = np.arange(4*3*2)

In [498]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [499]:
a = np.arange(1*2*5)

In [500]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [504]:
#Resizing

a = np.arange(4)

In [505]:
a.resize((8,))

In [506]:
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [507]:
b = a

In [508]:
a.resize((4,))

ValueError: cannot resize an array that references or is referenced
by another array in this way.  Use the resize function

In [512]:
#Sorting data

a = np.array([[5,4,6] , [2,3,2] ])
b = np.sort(a,axis=0)

In [513]:
b

array([[2, 3, 2],
       [5, 4, 6]])

In [514]:
a

array([[5, 4, 6],
       [2, 3, 2]])

In [515]:
a.sort(axis=1)

In [516]:
a

array([[4, 5, 6],
       [2, 2, 3]])

In [517]:
a.sort(axis=0)

In [518]:
a

array([[2, 2, 3],
       [4, 5, 6]])

In [519]:
#Sorting with Fancy Indexing

In [520]:
a = np.array([4,3,2,1,2])

In [521]:
j = np.argsort(a)

In [522]:
j

array([3, 2, 4, 1, 0], dtype=int64)

In [523]:
a

array([4, 3, 2, 1, 2])

In [524]:
a = np.array([4,3,1,2])

In [525]:
a

array([4, 3, 1, 2])

In [526]:
j = np.argsort(a)

In [527]:
j

array([2, 3, 1, 0], dtype=int64)

In [528]:
a[j]

array([1, 2, 3, 4])

In [529]:
a

array([4, 3, 1, 2])

In [530]:
a

array([4, 3, 1, 2])

In [531]:
a

array([4, 3, 1, 2])

In [532]:
a

array([4, 3, 1, 2])

In [533]:
a

array([4, 3, 1, 2])

In [534]:
a

array([4, 3, 1, 2])

In [535]:
b

array([[2, 3, 2],
       [5, 4, 6]])

In [536]:
a = np.array([1,3,2])

In [537]:
x.min

<function ndarray.min>

In [538]:
a.min()

1

In [539]:
a.max()

3

In [540]:
a.argmin()

0

In [541]:
a

array([1, 3, 2])

In [542]:
a.argmax

<function ndarray.argmax>

In [543]:
a.argmax()

1

In [544]:
a = np.array([[5,2,9] , [6,12,8]])

In [545]:
a

array([[ 5,  2,  9],
       [ 6, 12,  8]])

In [546]:
a.max(0)

array([ 6, 12,  9])

In [547]:
a.max()

12

In [548]:
a.min()

2

In [549]:
a.argmax()

4

In [550]:
a.argmin()

1

In [551]:
a.axis(1)

AttributeError: 'numpy.ndarray' object has no attribute 'axis'

In [552]:
a.axis=1

AttributeError: 'numpy.ndarray' object has no attribute 'axis'

In [560]:
a.sum(axis=0)

array([11, 14, 17])